name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t jerem097/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push jerem097/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save $DIGITAL_OCEAN_BUYTICKETS_CLUSTER_NAME
        env:
          DIGITAL_OCEAN_BUYTICKETS_CLUSTER_NAME: ${{ secrets.DIGITAL_OCEAN_BUYTICKETS_CLUSTER_NAME }}
      - run: kubectl rollout restart deployment expiration-depl
